### ISSUE TITLE
Tools Not working

### ISSUE THREAD

**Issue by brigsz** [agrc/daq-web-framework#21] opened 2017-02-06 20:46 UTC
Everyone was generally pretty pleased with the application, although as I mentioned last week I was unable to demo any of the tools.  I am not sure if it was due to the laptop I was using, UWDN, or the browser (although I tried both Chrome and Firefox).  It works great on my desktop work computer.

**Comment by woswald** [comment] 2017-02-06 21:03
Operating system:
Windows 10 Home
Version: 1607
OS build: 14393.693
Used on Lenovo ideapad Miix 700-12ISK

Browser:
Chrome 56.0.2924.87
Firefox 51.0.1

Expected Behavior:
After navigating to test.mapserv.utah.gov/daq in the browser and logging in with my UMD the map/app should load.  I should then be able to click on a tool icon (e.g. search, buffer) and utilize a functional tool.

Actual Behavior:
Chrome:
In Chrome after logging in with a UMD user id and password, the map/app never loads, a blank browser screen just persists.  

Firefox:
In Firefox after logging in with a UMD user id and password, the map/app does load, however when I click on each tool icon to use the tools, none of them work.  The attribute tables do appear when a point is clicked on, and I can see the associated documents lists.  However, when I try clicking add next to a document, in an attempted to attach a document,  I receive an error.
![image](https://cloud.githubusercontent.com/assets/7386943/22666231/ff011686-ec74-11e6-88d9-d5e7c769c611.png)

**Comment by woswald** [comment] 2017-02-06 21:07
It appears that the attachment error may be a separate issue.  I tested it again and it seem to only happen with some, not all, documents.

**Comment by steveoh** [comment] 2017-02-06 22:47
> It appears that the attachment error may be a separate issue. I tested it again and it seem to only happen with some, not all, documents.

Remember that the testing file server does not contain all of the documents.

Would you screenshot your network and console tab @woswald in the chrome browser that does not load please

**Comment by steveoh** [comment] 2017-02-16 16:19
ping @woswald

**Comment by woswald** [comment] 2017-02-16 17:05
Do you need me to do something for this issue?

**Comment by steveoh** [comment] 2017-02-16 17:06
> It appears that the attachment error may be a separate issue. I tested it again and it seem to only happen with some, not all, documents.

Remember that the testing file server does not contain all of the documents.

Would you screenshot your network and console tab @woswald in the chrome browser that does not load please

**Comment by woswald** [comment] 2017-02-16 17:07
How do I do that in chrome?

**Comment by woswald** [comment] 2017-02-16 17:11
Never mind, figured it out.

**Comment by woswald** [comment] 2017-02-16 17:13
![image 2](https://cloud.githubusercontent.com/assets/7386943/23032090/969bf03e-f430-11e6-8a00-3286b83eb186.png)

**Comment by woswald** [comment] 2017-02-16 17:15
![image 4](https://cloud.githubusercontent.com/assets/7386943/23032179/de27b71c-f430-11e6-9dcc-c7b5bf3d8e98.png)

**Comment by steveoh** [comment] 2017-02-16 17:20
ok thank you. `http://test.mapserv.utah.gov/content/dgrid1/util/touch.js` is missing the `daq` token in the url. I will look into this.

**Comment by steveoh** [comment] 2017-02-21 23:23
I'm going to close this as a duplicate of #16

**Closed as completed by steveoh** 2017-02-21 23:23 UTC
